#' Plot Seurat meta.data with scater::plotColData
#'
#' Convenience wrapper that makes Seurat metadata easy to plot using the
#' \code{scater::plotColData()} interface (i.e., \code{x}, \code{y}, and \code{colour_by}
#' aesthetics taken from \code{colData}). This function converts the Seurat object's
#' \code{@meta.data} into a minimal \code{SingleCellExperiment} and then calls
#' \code{scater::plotColData()}.
#'
#' @details
#' This function constructs a temporary \code{SingleCellExperiment} (including a dummy assay)
#' solely to reuse \code{scater::plotColData()}. There must be a better way to do this
#' using equivalent \code{ggplot2} but all of my attempts so far look way worse
#' than the ones generated by \code{scater}
#'
#' @param seurat_obj A Seurat object.
#' @param x Optional metadata column name used for the x-axis.
#' @param y One or more metadata column names used for the y-axis.
#' @param colour_by Optional metadata column name used for colouring.
#' @param x_angle Numeric; rotation angle for x-axis labels. Default 0.
#' @param combine Logical; if TRUE and \code{patchwork} is installed, combine multiple plots.
#' @param ncol Number of columns when combining plots (passed to \code{patchwork::wrap_plots}).
#' @param guides Guide collection behavior when combining plots (passed to \code{patchwork::wrap_plots}).
#' @param plot_titles Optional character vector of titles per \code{y}.
#' @param ... Additional arguments passed to \code{scater::plotColData()}.
#'
#' @return A \code{ggplot} object if \code{length(y) == 1}, otherwise a combined patchwork plot
#'   (if enabled and available) or a list of \code{ggplot} objects.
#'
#' @export
mds_so_plot_coldata <- mds_so_plot_coldata <- function(seurat_obj,
                                                       x = NULL,
                                                       y,
                                                       colour_by = NULL,
                                                       x_angle = 0,
                                                       combine = TRUE,
                                                       ncol = NULL,
                                                       guides = "collect",
                                                       plot_titles = NULL,
                                                       ...) {
  if (!inherits(seurat_obj, "Seurat")) {
    stop("seurat_obj must be a Seurat object.", call. = FALSE)
  }
  if (!requireNamespace("SingleCellExperiment", quietly = TRUE)) {
    stop("Package 'SingleCellExperiment' is required.", call. = FALSE)
  }
  if (!requireNamespace("scater", quietly = TRUE)) {
    stop("Package 'scater' is required.", call. = FALSE)
  }
  if (!requireNamespace("ggplot2", quietly = TRUE)) {
    stop("Package 'ggplot2' is required.", call. = FALSE)
  }

  # y can be length 1 or >1
  if (missing(y) || length(y) < 1) {
    stop("Argument 'y' must be one or more column names in seurat_obj@meta.data.", call. = FALSE)
  }
  y <- as.character(y)

  # Align metadata to cell order (and error if mismatch)
  md <- seurat_obj@meta.data
  cell_ids <- colnames(seurat_obj)

  idx <- match(cell_ids, rownames(md))
  if (anyNA(idx)) {
    missing_cells <- cell_ids[is.na(idx)]
    stop(
      "meta.data rownames do not match Seurat cell names (missing: ",
      paste(utils::head(missing_cells, 5), collapse = ", "),
      if (length(missing_cells) > 5) ", ..." else "",
      ").",
      call. = FALSE
    )
  }
  md <- md[idx, , drop = FALSE]

  # Column existence check across all inputs (c() drops NULLs)
  needed <- c(x, y, colour_by)
  miss <- setdiff(needed, colnames(md))
  if (length(miss)) {
    stop("Missing column(s) in seurat_obj@meta.data: ",
         paste(miss, collapse = ", "), call. = FALSE)
  }

  # 0 x N dummy assay so the SCE has the correct number of columns
  dummy <- matrix(0, nrow = 0, ncol = length(cell_ids))
  colnames(dummy) <- cell_ids

  # Build minimal SCE with colData only
  sce <- SingleCellExperiment::SingleCellExperiment(
    assays  = list(dummy = dummy),
    colData = md
  )

  # Build one plot per y
  plots <- lapply(seq_along(y), function(i) {
    yi <- y[i]
    p <- scater::plotColData(
      sce,
      x = x,
      y = yi,
      colour_by = colour_by,
      ...
    )
    if (!is.null(plot_titles) && length(plot_titles) >= i && !is.na(plot_titles[i])) {
      p <- p + ggplot2::ggtitle(plot_titles[i])
    }
    if (!is.null(x_angle) && x_angle != 0) {
      p <- p + ggplot2::theme(
        axis.text.x = ggplot2::element_text(angle = x_angle, hjust = 1, vjust = 1)
      )
    }
    p
  })

  # Return single plot directly
  if (length(plots) == 1L) return(plots[[1L]])

  # Optionally combine using patchwork if available
  if (isTRUE(combine) && requireNamespace("patchwork", quietly = TRUE)) {
    return(patchwork::wrap_plots(plots, ncol = ncol, guides = guides))
  }

  if (isTRUE(combine)) {
    message("patchwork not installed; returning a list of plots. ",
            "Install with install.packages('patchwork') to combine automatically.")
  }
  plots
}
